export const CATEGORIES = [
  'Alle', 'Handwerk & DIY', 'Kochen & Backen', 'Technik & Software',
  'Business', 'Fitness & Gesundheit', 'Garten', 'Finanzen', 'Kreativität'
]

export const GUIDES = [
  {
    id: '1',
    title: 'Perfekte Brotback-Anleitung für Zuhause',
    description: 'Von Sauerteig bis Baguette — diese umfassende Anleitung erklärt alle Techniken des Brotbackens. Mit Schritt-für-Schritt-Fotos, Temperaturkurven und Fehlerbehebung für 12 verschiedene Brotsorten.',
    longDescription: `Diese 47-seitige Anleitung ist das Ergebnis von über 200 Backversuchen. Du lernst die Grundprinzipien der Brotfermentation, die richtige Mehlauswahl und wie du auch ohne professionellen Ofen Bäckerei-Qualität erreichst.\n\nInhalt:\n• Grundlagen des Sauerteigs\n• 12 Rezepte von einfach bis fortgeschritten\n• Fehlerdiagnose mit Fotos\n• Ausrüstungsguide\n• Saisonale Anpassungen`,
    price: 8.90,
    category: 'Kochen & Backen',
    author: 'Maria Schneider',
    authorAvatar: 'MS',
    authorBio: 'Professionelle Bäckerin mit 15 Jahren Erfahrung',
    pages: 47,
    format: 'PDF',
    rating: 4.8,
    reviewCount: 234,
    downloads: 1840,
    tags: ['Brot', 'Backen', 'Sauerteig', 'Rezepte'],
    preview: true,
    featured: true,
    createdAt: '2024-09-15',
    coverColor: '#f0d4c2',
    icon: '🍞'
  },
  {
    id: '2',
    title: 'Holzregal selbst bauen — Komplettanleitung',
    description: 'Materialien, Werkzeuge, Schnittlisten und Montagepläne für 5 verschiedene Regaltypen. Alles was du brauchst um in einem Wochenende ein stabiles Holzregal zu bauen.',
    longDescription: `Jeder kann ein Regal bauen — mit der richtigen Anleitung. Diese 38-seitige PDF führt dich durch jeden Schritt, von der Planung bis zur Lackierung.\n\nInhalt:\n• Materialauswahl und Holzarten\n• 5 Regal-Designs\n• Maßgenaue Schnittlisten\n• Verbindungstechniken\n• Oberflächenbehandlung`,
    price: 12.50,
    category: 'Handwerk & DIY',
    author: 'Thomas Müller',
    authorAvatar: 'TM',
    authorBio: 'Schreinermeister und DIY-Blogger',
    pages: 38,
    format: 'PDF',
    rating: 4.6,
    reviewCount: 189,
    downloads: 1320,
    tags: ['Holz', 'Regal', 'DIY', 'Werkzeug'],
    preview: true,
    featured: true,
    createdAt: '2024-10-02',
    coverColor: '#d8f3dc',
    icon: '🪚'
  },
  {
    id: '3',
    title: 'Excel Mastery: Pivot-Tabellen & Dashboards',
    description: 'Von Einsteiger zu Profi in 6 Stunden. Diese Anleitung deckt alles von SVERWEIS bis Power Query ab, inklusive 15 Download-Vorlagen für Dashboards.',
    longDescription: `Excel ist mächtiger als die meisten ahnen. Diese 62-seitige Anleitung zeigt dir die Features, die Profis täglich nutzen.\n\nInhalt:\n• Pivot-Tabellen von Grund auf\n• Bedingte Formatierung\n• Power Query Grundlagen\n• 15 Dashboard-Vorlagen\n• VBA-Einführung`,
    price: 19.90,
    category: 'Technik & Software',
    author: 'Sarah Klein',
    authorAvatar: 'SK',
    authorBio: 'Business Analyst und Excel-Trainerin',
    pages: 62,
    format: 'PDF + XLSX',
    rating: 4.9,
    reviewCount: 412,
    downloads: 3200,
    tags: ['Excel', 'Tabellen', 'Dashboard', 'Business'],
    preview: true,
    featured: true,
    createdAt: '2024-08-20',
    coverColor: '#e6f1fb',
    icon: '📊'
  },
  {
    id: '4',
    title: 'Freelancer Starterkit: Verträge & Preise',
    description: 'Rechtssichere Musterverträge, Angebotsvorlagen, Stundenpreisrechner und ein kompletter Leitfaden für den Start als Freelancer in Deutschland.',
    longDescription: `Der schwierigste Teil des Freelancens ist der Anfang. Diese 54-seitige Anleitung plus Vorlagen gibt dir alles was du brauchst.\n\nInhalt:\n• 3 Musterverträge (DE)\n• Angebots- und Rechnungsvorlagen\n• Stundenpreiskalkulator\n• Steuergrundlagen für Freelancer\n• Akquise-Strategie`,
    price: 24.90,
    category: 'Business',
    author: 'Jonas Weber',
    authorAvatar: 'JW',
    authorBio: 'Freelancer seit 10 Jahren, Coach',
    pages: 54,
    format: 'PDF + DOCX',
    rating: 4.7,
    reviewCount: 298,
    downloads: 2100,
    tags: ['Freelance', 'Business', 'Verträge', 'Finanzen'],
    preview: false,
    featured: true,
    createdAt: '2024-11-01',
    coverColor: '#faeeda',
    icon: '💼'
  },
  {
    id: '5',
    title: 'Heimtraining ohne Geräte: 12-Wochen-Plan',
    description: 'Strukturierter Trainingsplan mit täglichen Workouts, Ernährungsplan und Fortschritts-Tracking. Für alle Fitnesslevel geeignet, keine Ausrüstung nötig.',
    longDescription: `Fitness ohne Gym ist möglich — wenn du weißt wie. Dieser 44-seitige Plan wurde von einem zertifizierten Trainer entwickelt.\n\nInhalt:\n• 12-Wochen Trainingsplan\n• 80+ Übungen mit Abbildungen\n• Ernährungsgrundlagen\n• Tracking-Vorlagen\n• Modifikationen für alle Level`,
    price: 14.90,
    category: 'Fitness & Gesundheit',
    author: 'Lisa Berg',
    authorAvatar: 'LB',
    authorBio: 'Zertifizierte Personal Trainerin',
    pages: 44,
    format: 'PDF',
    rating: 4.5,
    reviewCount: 167,
    downloads: 1560,
    tags: ['Fitness', 'Training', 'Gesundheit', 'Ernährung'],
    preview: true,
    featured: false,
    createdAt: '2024-10-18',
    coverColor: '#fbeaf0',
    icon: '💪'
  },
  {
    id: '6',
    title: 'Gemüsegarten planen & anlegen',
    description: 'Monatskalender, Beetpläne, Pflanzabstände und Pflegeanleitungen für 30 Gemüsesorten. Der komplette Guide für deinen ersten Gemüsegarten.',
    longDescription: `Frisches Gemüse vom eigenen Garten — dieser Guide macht es möglich, auch für Anfänger.\n\nInhalt:\n• Gartenplanung mit Zeichnungen\n• Aussaatkalender (Monat für Monat)\n• 30 Gemüseprofile\n• Schädlingsbekämpfung\n• Kompostierung`,
    price: 9.90,
    category: 'Garten',
    author: 'Klaus Fischer',
    authorAvatar: 'KF',
    authorBio: 'Landschaftsgärtner und Permakulturbauer',
    pages: 52,
    format: 'PDF',
    rating: 4.4,
    reviewCount: 143,
    downloads: 980,
    tags: ['Garten', 'Gemüse', 'Pflanzen', 'Natur'],
    preview: true,
    featured: false,
    createdAt: '2024-09-28',
    coverColor: '#d8f3dc',
    icon: '🥕'
  },
  {
    id: '7',
    title: 'Persönliche Finanzen im Griff: Budget-System',
    description: 'Ein bewährtes Budget-System mit Excel-Vorlagen, Sparstrategien und Schritt-für-Schritt-Anleitung zum Aufbau eines Notgroschens und ersten Investitionen.',
    longDescription: `Finanzielle Kontrolle beginnt mit einem System. Dieser Guide zeigt dir wie.\n\nInhalt:\n• 50/30/20-Regel erklärt\n• Budget-Tracker Vorlage\n• Schulden tilgen Strategie\n• Notgroschen aufbauen\n• ETF-Grundlagen`,
    price: 16.90,
    category: 'Finanzen',
    author: 'Anna Schmidt',
    authorAvatar: 'AS',
    authorBio: 'Finanzberaterin und Bloggerin',
    pages: 41,
    format: 'PDF + XLSX',
    rating: 4.8,
    reviewCount: 321,
    downloads: 2800,
    tags: ['Finanzen', 'Budget', 'Sparen', 'Investieren'],
    preview: false,
    featured: false,
    createdAt: '2024-11-10',
    coverColor: '#e6f1fb',
    icon: '💰'
  },
  {
    id: '8',
    title: 'Aquarell malen lernen: Grundkurs',
    description: 'Von der Materialauswahl bis zur fertigen Landschaft. 20 Übungsaufgaben mit steigendem Schwierigkeitsgrad, mit Referenzbildern und Schritt-für-Schritt-Anleitungen.',
    longDescription: `Aquarell ist zugänglich für jeden — mit der richtigen Anleitung. Dieser 58-seitige Guide begleitet dich vom ersten Pinselstrich.\n\nInhalt:\n• Materialguide & Empfehlungen\n• Farblehre und Mischungen\n• 20 geführte Übungen\n• Techniken (Wet-on-wet, Layering)\n• Häufige Fehler vermeiden`,
    price: 11.90,
    category: 'Kreativität',
    author: 'Marie Hoffmann',
    authorAvatar: 'MH',
    authorBio: 'Künstlerin und Kunstlehrerin',
    pages: 58,
    format: 'PDF',
    rating: 4.6,
    reviewCount: 201,
    downloads: 1450,
    tags: ['Aquarell', 'Malen', 'Kunst', 'Kreativ'],
    preview: true,
    featured: false,
    createdAt: '2024-10-05',
    coverColor: '#fbeaf0',
    icon: '🎨'
  }
]

export const getGuideById = (id) => GUIDES.find(g => g.id === id)
export const getFeaturedGuides = () => GUIDES.filter(g => g.featured)
export const getGuidesByCategory = (cat) => cat === 'Alle' ? GUIDES : GUIDES.filter(g => g.category === cat)
