[build]
  base = "guide"
  publish = "frontend/dist"
  command = "cd backend && npm install && cd ../frontend && npm install && npm run build"
  functions = "backend/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
